You-HsiangWang/mmmh63_Movwe

css/Carousel_3.css, css/Carousel_4.css, css/Home.css, css/Nav.css, css/actor_02.css, css/single_movie.css, css/wish_page.css, html/Home-0523.html, js/home.js
=> 0524_ver1.1_首頁優化_nav修改

css/Nav.css
=> 0525_ver1.2_nav_css513行100vh修正

member-info-index-got.php, member-info-index.php
=> 0525_ver1.0_上傳member-info-php_高

css/Nav.css, css/reset.css, css/slider.css, html/Home-0523.html, html/index-forum.html
=> 0525_v1.4_nav_更新_笠

css/Nav.css, html/Home-0523.html
=> 0525_v1.5_nav更新

css/reset.css, html/Home-0523.html
=> 0525_ver1.6_nav更新

.gitignore, json/dl_vid_kr_mov.php
影劇圖片和資料表已經完成。
請大家去sql到database
跟雲端印諜下載圖庫
[雲端連結](https://drive.google.com/drive/folders/1U8yUhCoeVLd9RiDqSWeXkvZ64hnvun3w?usp=sharing)
=> 0525_ver2.7_更新抓圖片php_翔

.gitignore, api_home_ottfilter.php, home_ottfilter.php
=> 0526_ver2.7_test_翔

api_home_ottfilter.php, css/Home.css, css/filter_function.css, home_ottfilter.php, index_home.php, js/filter_function.js, parts/movwe_filter_function.php
維持filter所必要的檔案
/parts/movwe_filter_funtion.php
js/filter_funtion.js
css/filter_function.css
api_ott_function.php
=> 0528_ver2.9更新filterfunction_翔

single_movie.php, wish_home.php
=> 0528_ver2.0_睡前確認

css/footer.css, member-info-index-got.php, member-info-index.php, parts/movwe_footer.php
footer.css修改
footer底下a連結取消→改成cursor
=> 0530_ver2.0_footer修改＿高

index_home.php, store.php
=> 0531_ver2.7_加連結_笠

css/footer.css, css/member-info-php.css, member-info-index-got.php, member-info-index.php
將頁籤切換方式a連結刪除，終於不會再跳來跳去惹(灑花灑花~)
會員頁面細節處理
=> 0531_ver2.4_會員頁優化＿高

member-info-index-got.php, member-info-index.php
=> 0602_ver2.7_會員頁我的點數欄位串資料庫＿高

api_home_ottfilter.php, css/Carousel_6.css, css/Home.css, css/filter_function.css, css/search__filter.css, index_home.php, js/Carousel_6.js, js/Nav.js, js/lightbox.js, search_page.php, single_movie.php, wish_page.php
=> 0602_ver3.2_資訊更新和修改＿笠

api_member_info_db.php, member-info-index.php
=> 0602_ver2.8_會員頁真的串資料庫＿高

css/member-info-php.css, member-info-index.php
1.歷史訂單修改
2.訂單編號 highlight
3.討論區 一鍵刪除
4.儲存成功提示框
=> 0603_ver2.9_會員頁修改＿高

css/member-info-php.css, member-info-index.php, sql/member_has_wishlist.sql, sql/wishlist.sql
會runrun的進度條
許願清單sql檔: wishlist.sql / member_has_wishlist.sql
=> 0604_ver3.2_許願清單(會runrun的進度條)+許願sql＿高

css/member-info-php.css, member-info-index.php
會員頁debug
1. 收藏文章-安尼亞已刪除
2. 文章區手機版爆版問題_已排除
3. textarea斷行問題
=> 0606_ver3.6_會員頁-textarea斷行問題＿高

css/Carousel_7.css, css/reset.css, css/search__filter.css, forum.php, index_home.php, search_page copy.php
=> 0606__ver3.9_預演前整理＿笠

member-info-index.php
=> 0606_ver3.7_會員頁籤-手機調整＿高
